const STORE_KEY = 'focusflow-v2';
const defaults = { theme: 'light', tasks: [], note: '', sessions: 0, focusMinutes: 0, sessionDays: [], intent: '' };
let state = { ...defaults, ...(() => { try { return JSON.parse(localStorage.getItem(STORE_KEY) || '{}') } catch { return {} } })() };
let timerId = null, timerSeconds = 1500, timerRunning = false, currentMode = 'focus';
const modeSeconds = { focus: 1500, short: 300, long: 900 };

function persist() { localStorage.setItem(STORE_KEY, JSON.stringify(state)) }
function $(id) { return document.getElementById(id) }
function currentDateKey(d = new Date()) { return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}` }
function formatDate(d = new Date()) { return new Intl.DateTimeFormat('en-US', { weekday: 'long', month: 'long', day: 'numeric' }).format(d) }
function greeting() { const h = new Date().getHours(); return h < 12 ? 'GOOD MORNING' : h < 18 ? 'GOOD AFTERNOON' : 'GOOD EVENING' }
function applyTheme() { document.body.classList.toggle('dark', state.theme === 'dark'); const b = $('themeBtn'); if (b) { const dark = state.theme === 'dark'; b.innerHTML = `${dark ? '☼' : '◐'} <span>${dark ? 'Light' : 'Dark'}</span>`; b.setAttribute('aria-label', `Switch to ${dark ? 'light' : 'dark'} theme`) } }
function updateTheme() { state.theme = state.theme === 'light' ? 'dark' : 'light'; persist(); applyTheme() }
function recordSession(minutes) { state.sessions++; state.focusMinutes += minutes; const key = currentDateKey(); if (!state.sessionDays.includes(key)) state.sessionDays.push(key); persist() }
function streak() { const days = new Set(state.sessionDays || []); let cursor = new Date(), n = 0; while (days.has(currentDateKey(cursor))) { n++; cursor.setDate(cursor.getDate() - 1) } return n }
function priorityLabel(p) { return p === 'high' ? 'High' : p === 'low' ? 'Low' : 'Medium' }
function escapeHtml(s) { return String(s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[c])) }

function renderHome() {
  $('greeting') && ($('greeting').textContent = greeting()); $('dateLabel') && ($('dateLabel').textContent = formatDate());
  const done = state.tasks.filter(t => t.done && (t.createdAt ? currentDateKey(new Date(t.createdAt)) === currentDateKey() : true)).length;
  $('taskCount') && ($('taskCount').textContent = done); $('sessionCount') && ($('sessionCount').textContent = state.sessions || 0); $('minuteCount') && ($('minuteCount').textContent = state.focusMinutes || 0); $('streakCount') && ($('streakCount').textContent = streak());
  const list = $('taskPreview'); if (list) { const pending = state.tasks.filter(t => !t.done).slice(0, 4); list.innerHTML = pending.length ? pending.map(t => `<div class="preview-task"><span class="priority-dot priority-${t.priority}"></span><span class="task-text">${escapeHtml(t.text)}</span></div>`).join('') : '<div class="empty-state">No active tasks. Add a few priorities for today.</div>' }
  const note = $('notePreview'); if (note) note.textContent = state.note || 'Your saved note will appear here.';
  $('taskTrend') && ($('taskTrend').textContent = done ? `${done} completed today` : 'Start with one small win'); $('sessionTrend') && ($('sessionTrend').textContent = state.sessions ? `${state.sessions} session${state.sessions === 1 ? '' : 's'} logged` : 'Start your first session');
}
function addTask(text, priority = 'medium') { state.tasks.unshift({ id: crypto.randomUUID ? crypto.randomUUID() : Date.now().toString(), text: text.trim(), priority, done: false, createdAt: Date.now() }); persist(); renderTasks(); renderHome() }
function renderTasks(filter = 'all') {
  const list = $('taskList'); if (!list) return; const query = ($('taskSearch')?.value || '').trim().toLowerCase(); let tasks = state.tasks;
  if (filter === 'active') tasks = tasks.filter(t => !t.done); if (filter === 'completed') tasks = tasks.filter(t => t.done); if (query) tasks = tasks.filter(t => t.text.toLowerCase().includes(query));
  list.innerHTML = tasks.length ? tasks.map(t => `<div class="task-row ${t.done ? 'completed' : ''}" data-id="${escapeHtml(t.id)}"><div class="task-main"><button class="check-btn" data-action="toggle" aria-label="Mark ${t.done ? 'active' : 'complete'}">${t.done ? '✓' : ''}</button><span class="priority-dot priority-${t.priority}" title="${priorityLabel(t.priority)}"></span><span class="task-text">${escapeHtml(t.text)}</span></div><button class="delete-task" data-action="delete" aria-label="Delete task">×</button></div>`).join('') : '<div class="empty-state">Nothing here yet.</div>';
  $('taskTotal') && ($('taskTotal').textContent = state.tasks.length)
}
function notesInit() { const input = $('noteInput'); if (!input) return; input.value = state.note || ''; updateNoteMeta(); input.addEventListener('input', () => { state.note = input.value; persist(); updateNoteMeta(); const status = $('saveStatus'); if (status) { status.textContent = 'Saving…'; clearTimeout(window._save); window._save = setTimeout(() => status.textContent = 'Saved', 400) } }) }
function updateNoteMeta() { const input = $('noteInput'); if (!input) return; const words = input.value.trim() ? input.value.trim().split(/\s+/).length : 0; $('wordCount') && ($('wordCount').textContent = `${words} word${words === 1 ? '' : 's'}`); $('noteMeta') && ($('noteMeta').textContent = `${input.value.length} characters`) }
function initTimer() { const intent = $('sessionIntent'); if (intent) { intent.value = state.intent || ''; intent.addEventListener('input', () => { state.intent = intent.value; persist() }) } renderTimer(); document.querySelectorAll('.mode-btn').forEach(b => b.addEventListener('click', () => { currentMode = b.dataset.mode; timerSeconds = modeSeconds[currentMode]; timerRunning = false; clearInterval(timerId); document.querySelectorAll('.mode-btn').forEach(x => x.classList.toggle('active', x === b)); renderTimer() })); $('timerToggle')?.addEventListener('click', toggleTimer); $('timerReset')?.addEventListener('click', resetTimer); document.addEventListener('keydown', e => { if (e.code === 'Space' && document.body.dataset.page === 'timer' && !['TEXTAREA', 'INPUT', 'SELECT', 'BUTTON'].includes(document.activeElement.tagName)) { e.preventDefault(); toggleTimer() } }) }
function renderTimer() { const m = Math.floor(timerSeconds / 60), s = timerSeconds % 60; if ($('timer')) $('timer').textContent = `${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`; $('timerLabel') && ($('timerLabel').textContent = currentMode === 'focus' ? 'FOCUS' : currentMode === 'short' ? 'SHORT BREAK' : 'LONG BREAK'); $('timerStatus') && ($('timerStatus').textContent = timerRunning ? 'Deep work in progress.' : 'Ready when you are.'); $('timerToggle') && ($('timerToggle').textContent = timerRunning ? 'Pause session' : 'Start session'); $('timerSessions') && ($('timerSessions').textContent = state.sessions); $('timerMinutes') && ($('timerMinutes').textContent = state.focusMinutes); $('checkpoint') && ($('checkpoint').textContent = currentMode === 'focus' ? '25 minutes of deep work' : currentMode === 'short' ? 'Reset and breathe' : 'Recover before your next sprint'); const ring = document.querySelector('.timer-ring'); if (ring) ring.style.setProperty('--progress', `${((modeSeconds[currentMode] - timerSeconds) / modeSeconds[currentMode]) * 360}deg`); document.title = `${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')} · FocusFlow` }
function toggleTimer() { if (timerRunning) { timerRunning = false; clearInterval(timerId); renderTimer(); return } timerRunning = true; renderTimer(); timerId = setInterval(() => { timerSeconds--; if (timerSeconds <= 0) { clearInterval(timerId); timerRunning = false; if (currentMode === 'focus') recordSession(modeSeconds.focus / 60); const finishedMode = currentMode; timerSeconds = modeSeconds[currentMode]; renderTimer(); const message = finishedMode === 'focus' ? 'Focus session complete. Nice work.' : 'Break complete. Ready for the next block.'; if ('Notification' in window && Notification.permission === 'granted') new Notification('FocusFlow', { body: message }); else alert(message); renderHome(); return } renderTimer() }, 1000); if ('Notification' in window && Notification.permission === 'default') Notification.requestPermission().catch(() => { }) }
function resetTimer() { timerRunning = false; clearInterval(timerId); timerSeconds = modeSeconds[currentMode]; renderTimer() }
function wireTasks() { const form = $('taskForm'); if (form) form.addEventListener('submit', e => { e.preventDefault(); const input = $('taskInput'); if (input.value.trim()) { addTask(input.value, $('priorityInput').value); input.value = ''; input.focus() } }); let filter = 'all'; document.querySelectorAll('.filter-btn').forEach(b => b.addEventListener('click', () => { filter = b.dataset.filter; document.querySelectorAll('.filter-btn').forEach(x => { x.classList.toggle('active', x === b); x.setAttribute('aria-pressed', x === b ? 'true' : 'false') }); renderTasks(filter) })); $('taskSearch')?.addEventListener('input', () => renderTasks(filter)); $('taskList')?.addEventListener('click', e => { const row = e.target.closest('.task-row'); if (!row) return; const idx = state.tasks.findIndex(t => t.id === row.dataset.id); if (idx < 0) return; if (e.target.closest('[data-action="toggle"]')) state.tasks[idx].done = !state.tasks[idx].done; if (e.target.closest('[data-action="delete"]')) state.tasks.splice(idx, 1); persist(); renderTasks(filter); renderHome() }); $('clearCompletedBtn')?.addEventListener('click', () => { state.tasks = state.tasks.filter(t => !t.done); persist(); renderTasks(filter); renderHome() }) }
function registerPwa() { if ('serviceWorker' in navigator) window.addEventListener('load', () => { const script = document.querySelector('script[src]'); if (script) navigator.serviceWorker.register(new URL('sw.js', script.src)).catch(error => console.error('FocusFlow service worker registration failed:', error)) }) }
function globalWire() { applyTheme(); $('themeBtn')?.addEventListener('click', updateTheme); $('clearDataBtn')?.addEventListener('click', () => { if (confirm('Reset all FocusFlow data on this device?')) { localStorage.removeItem(STORE_KEY); location.reload() } }) }
document.addEventListener('DOMContentLoaded', () => { globalWire(); registerPwa(); const page = document.body.dataset.page; if (page === 'home') renderHome(); if (page === 'tasks') { wireTasks(); renderTasks() } if (page === 'notes') { notesInit(); $('clearNoteBtn')?.addEventListener('click', () => { if (confirm('Clear this note?')) { state.note = ''; persist(); notesInit() } }) } if (page === 'timer') initTimer() });
